apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: psql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: psql-database
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: psql
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-database
  namespace: default
  labels: 
    app: psql
spec:
  selector:
    matchLabels:
      app: psql
  strategy:
    type: Recreate 
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql-database
        image: nathapaulino/aps_db
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: psql-secrets
        volumeMounts:
        - name: psql-persistence-storage
          mountPath: /var/lib/psql
      volumes:
      - name: psql-persistence-storage
        persistentVolumeClaim:
          claimName: psql-pv-claim
---